name: Publish package

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun i
      - name: Run build
        run: bun run build
      - name: Run tests
        run: bun run test:types
      - uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/package.json
          access: public
          tag: latest
          strategy: upgrade
